### ISSUE TITLE
test_video.rb renderer flags

### ISSUE THREAD

**Issue by incompetentcoder** [ohai/ruby-sdl2#10]
Hello.
I found an issue when trying to run the test_video.rb sample complaining about unknown constants, attached a patch for test_video.rb to fix the renderer flags.

https://gist.github.com/incompetentcoder/cbd700174dc6b35ae57b7e2604f46139

**Comment by ohai** [comment]
Thank you for your report.

This problem is fixed by 341d0444bf0fe80a4959ddd538150c51351b7baa.
