### ISSUE TITLE
SDL2::Surface.load method missing in RubyGems version 0.3.2

### ISSUE THREAD

**Issue by DataKinds** [ohai/ruby-sdl2#12]
Hi,

The `SDL2::Surface.load()` method is missing from version 0.3.2 downloaded from Ruby Gems. This breaks a few of the example scripts, including but not limited to `testsprite.rb`.

**Comment by ohai** [comment]
`SDL_image` library is  required to use `SDL2::Surface.load`. I think that you do not install the library. Please check the install log.
