### ISSUE TITLE
Documentation needs to be updated/regenerated

### ISSUE THREAD

**Issue by DataKinds** [ohai/ruby-sdl2#13]
Hello, 

Much of the documentation refers to objects or methods that do not exist. For example, the documentation for the [`create_renderer`](https://ohai.github.io/ruby-sdl2/doc-en/SDL2/Window.html#create_renderer-instance_method) function links to a page that should not exist, when it should be linking [here](https://ohai.github.io/ruby-sdl2/doc-en/SDL2/Renderer/Flags.html).

**Comment by ohai** [comment]
Thank you for your report. I fixed the link. 

I also check dead-links by a machine checker, and the result is green.
If you have another problem, please report it.
