### ISSUE TITLE
TTF, and Mixer are missing from version 0.3.2.

### ISSUE THREAD

**Issue by ghost** [ohai/ruby-sdl2#14]
I installed the latest version of ruby-sdl2(version 0.3.2), and my application broke as a result. I got the error `uninitialized constant SDL2::TTF (NameError)`. What happend? Everything worked perfectly in the last version?

**Comment by ohai** [comment]
Thank you for your report. Probably this is a bug introduced by PR #8. I will fix it later.

**Comment by ghost** [comment]
Thank you.

**Comment by ohai** [comment]
The problem is fixed. Please use the new version 0.3.3 on rubygems.org.
