### ISSUE TITLE
Opinion about modernizing the gem

### ISSUE THREAD

**Issue by smortex** [ohai/ruby-sdl2#18]
Hey @ohai 

We are planning to use ruby-sdl2 in a project and contribute haptic support, but are currently somewhat blocked because the gem is organized in a legacy fashion and does not integrate gracefully with a Gemfile.

People have previously worked on this but seems to have never opened a PR:
https://github.com/furunkel/ruby-sdl2/commit/4bf01214049dce1e272d0cde55283515fd2e8190

The code has diverged, and I am wondering if you would be inclined to accept a PR that integrate this work on top of the current code?  If so, I could work on it.

Thank you for your feedback!

**Comment by ohai** [comment]
Hello, @smortex 

- The PR contains the removal of m4, but m4 is required for the yard documentation generation.  That's the main reason to reject this PR. I already discuss the problem in https://github.com/ohai/ruby-sdl2/pull/3 .
- This PR introduces the dependency to rake-compiler gem. I think that we need a special reason to introduce a new dependency to the project. We simply make a file `rubysdl2.gemspec` and modify `Rakefile` if we want to use Gemfile. Such a change is acceptable.

**Comment by smortex** [comment]
D'oh, I failed to spot #3 :roll_eyes: 

Thanks for the feedback!  Will take this into account
