### ISSUE TITLE
SDL_WaitEvent()?

### ISSUE THREAD

**Issue by RinGotou** [ohai/ruby-sdl2#22]
Hello! I want to build a new project with this gem, but seems I can't find some function binding for SDL_WaitEvent and I can find out SDL2::Event.poll only. Is there some reason about the missing of this function?

**Comment by ohai** [comment]
Hello. That is because I have no use-case of WaitEvent. I think that polling events are more useful in many cases. If you have a good use-case, I will add the interface to SDL_WaitEvent.

**Comment by RinGotou** [comment]
Thanks for response, I'm currently constructing in a very slow status, but I'll be very happy if you add this binding! (I'm not familiar with Ruby native extension development)
