### ISSUE TITLE
scancode

### ISSUE THREAD

**Issue by gbbnfhb** [ohai/ruby-sdl2#25]
key.c :80
    scancode = NUM2UINT(code);
    if (scancode >= SDL_NUM_SCANCODES) 
        rb_raise(rb_eArgError, "too large scancode %d", scancode);

必ずしもSDL_NUM_SCANCODES以下になるわけではないみたいですが・・
SDLキーコード一覧表
http://sdl2referencejp.osdn.jp/SDLKeycodeLookup.html

**Comment by ohai** [comment]
作者のohaiです．

SDLには keycode と scancode の二種類がありまして，そこは scancode  に対応してます． http://sdl2referencejp.osdn.jp/CategoryKeyboard.html なども参照してください．

**Comment by gbbnfhb** [comment]
あーわかりました
SDL2::Key::PAGEDOWN　でなくて
SDL2::Key::Scan::PAGEDOWN　ですね
しかしわかりずらい、ありがとうございました

**Comment by ohai** [comment]
まあSDLのこの部分は元々わかりにくいので難しいですね
