### ISSUE TITLE
module load error

### ISSUE THREAD

**Issue by physaris** [ohai/ruby-sdl2#4]
Hi, ohai
I'd like to thanks for the work first. Recently I have installed this gem, and build with mingw on Windows 7 64bit, all the process was success. But when I run the test comes with this gem, it fails.
The output are listed below, do you have any idea what's wrong with my installation?

My environment was:
- Windows 7 64bit
- rubyinstaller-2.3.0-x64
- DevKit-mingw64-64-4.7.2
- SDL2-2.0.4 with image, mixer, ttf

My build steps are:
git clone https://github.com/ohai/ruby-sdl2.git
cd ruby-sdl2
rake gem
gem install pkg/ruby-sdl2-x.y.z.gem -- --with-opt-include=G:\SDL2-2.0.4\x86_64-w64-mingw32\include\SDL2 --with-opt-lib=G:\SDL2-2.0.4\x86_64-w64-mingw32\lib

Command and output:
G:\RubyJY\ruby-sdl2\sample>ruby test_surface.rb
G:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
: 126: 找不到指定的模块。   - G:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby-sdl2-0
.3.0/lib/sdl2_ext.so (LoadError)
        from G:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in`require'
        from G:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/ruby-sdl2-0.3.0/lib/sdl2.rb:
1:in `<top (required)>'
        from G:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:12
7:in`require'
        from G:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:12
7:in `rescue in require'
        from G:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40
:in`require'
        from test_surface.rb:1:in `<main>'

**Comment by ohai** [comment]
Hello,

One possibility is not to find DLLs from your program.
Please try to copy all SDL, SDL_mixer, SDL_ttf, and SDL_image DLLs into the current directory and run the sample program again.

**Comment by ohai** [comment]
Close this issue because of no reply.
